require:
  - ./rubocop/cop/security/no_reflection_methods.rb

inherit_from: .rubocop_todo.yml
inherit_gem:
  rubocop-shopify: rubocop.yml

plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - '.ruby-lsp/**/*'

# Allow flexible naming in examples directory
Naming/FileName:
  Exclude:
    - 'examples/**/*'

Security/NoReflectionMethods:
  Enabled: true
  Exclude:
  - lib/claude_swarm/**/*
  - lib/claude_swarm.rb