name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      claude_swarm_changed: ${{ steps.filter.outputs.claude_swarm }}
      swarm_sdk_changed: ${{ steps.filter.outputs.swarm_sdk }}
      swarm_memory_changed: ${{ steps.filter.outputs.swarm_memory }}
      swarm_cli_changed: ${{ steps.filter.outputs.swarm_cli }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            claude_swarm:
              - 'lib/claude_swarm.rb'
              - 'lib/claude_swarm/**'
              - 'test/**'
              - '!test/swarm_sdk/**'
              - '!test/swarm_memory/**'
              - '!test/swarm_cli/**'
              - 'claude_swarm.gemspec'
            swarm_sdk:
              - 'lib/swarm_sdk.rb'
              - 'lib/swarm_sdk/**'
              - 'swarm_sdk.gemspec'
              - 'test/swarm_sdk/**'
            swarm_memory:
              - 'lib/swarm_memory.rb'
              - 'lib/swarm_memory/**'
              - 'swarm_memory.gemspec'
              - 'test/swarm_memory/**'
            swarm_cli:
              - 'lib/swarm_cli.rb'
              - 'lib/swarm_cli/**'
              - 'swarm_cli.gemspec'
              - 'test/swarm_cli/**'

  test-claude-swarm:
    needs: detect-changes
    if: needs.detect-changes.outputs.claude_swarm_changed == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3', '3.4']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Install ripgrep
      run: sudo apt-get update && sudo apt-get install -y ripgrep

    - name: Install Claude Code
      run: npm install -g @anthropic-ai/claude-code

    - name: Run ClaudeSwarm tests
      run: bundle exec rake claude_swarm:test

    - name: Run ClaudeSwarm linter
      run: bundle exec rake claude_swarm:rubocop

    - name: Test ClaudeSwarm loads without bundler
      run: |
        gem build claude_swarm.gemspec
        gem install ./claude_swarm-*.gem
        ruby -e "require 'claude_swarm'"

    - name: Test in isolated environment with fresh bundle
      run: |
        mkdir -p tmp/gem_test
        cd tmp/gem_test
        cat > Gemfile <<EOF
        source 'https://rubygems.org'
        gem 'claude_swarm', path: '../..'
        EOF
        bundle install
        bundle exec ruby -e "require 'claude_swarm'; puts 'Gem loaded successfully'"
        bundle exec claude-swarm version

  test-swarm-sdk:
    needs: detect-changes
    if: needs.detect-changes.outputs.swarm_sdk_changed == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3', '3.4']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Install ripgrep
      run: sudo apt-get update && sudo apt-get install -y ripgrep

    - name: Run SwarmSDK tests
      run: bundle exec rake swarm_sdk:test

    - name: Run SwarmSDK linter
      run: bundle exec rake swarm_sdk:rubocop
    
    - name: Test SwarmSDK gem loads without bundler
      run: |
        gem build swarm_sdk.gemspec
        gem install ./swarm_sdk-*.gem
        ruby -e "require 'swarm_sdk'"

    - name: Test in isolated environment with fresh bundle
      run: |
        mkdir -p tmp/gem_test
        cd tmp/gem_test
        cat > Gemfile <<EOF
        source 'https://rubygems.org'
        gem 'swarm_sdk', path: '../..'
        EOF
        bundle install
        bundle exec ruby -e "require 'swarm_sdk'; puts 'Gem loaded successfully'"

  test-swarm-memory:
    needs: detect-changes
    if: needs.detect-changes.outputs.swarm_memory_changed == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3', '3.4']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y ripgrep build-essential

    - name: Run SwarmMemory tests
      run: bundle exec rake swarm_memory:test

    - name: Run SwarmMemory linter
      run: bundle exec rake swarm_memory:rubocop
    
    - name: Test SwarmMemory gem loads without bundler
      run: |
        gem build swarm_memory.gemspec
        gem install ./swarm_memory-*.gem
        ruby -e "require 'swarm_memory'"

    - name: Test in isolated environment with fresh bundle
      run: |
        mkdir -p tmp/gem_test
        cd tmp/gem_test
        cat > Gemfile <<EOF
        source 'https://rubygems.org'
        gem 'swarm_memory', path: '../..'
        EOF
        bundle install
        bundle exec ruby -e "require 'swarm_memory'; puts 'Gem loaded successfully'"

  test-swarm-cli:
    needs: detect-changes
    if: needs.detect-changes.outputs.swarm_cli_changed == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3', '3.4']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Install ripgrep
      run: sudo apt-get update && sudo apt-get install -y ripgrep

    - name: Run SwarmCLI tests
      run: bundle exec rake swarm_cli:test

    - name: Run SwarmCLI linter
      run: bundle exec rake swarm_cli:rubocop
    
    - name: Test SwarmCLI gem loads without bundler
      run: |
        gem build swarm_cli.gemspec
        gem install ./swarm_cli-*.gem
        ruby -e "require 'swarm_cli'"

    - name: Test in isolated environment with fresh bundle
      run: |
        mkdir -p tmp/gem_test
        cd tmp/gem_test
        cat > Gemfile <<EOF
        source 'https://rubygems.org'
        gem 'swarm_cli', path: '../..'
        EOF
        bundle install
        bundle exec ruby -e "require 'swarm_cli'; puts 'Gem loaded successfully'"
        bundle exec swarm --version
